### PR TITLE
Fortune cookies banners & streak text improvements

### PR DESCRIPTION
**Pull request by Rchardon**

### CODE REVIEW

**Comment by Zamiell** [comment]
is ui_fortunepaper.anm2 a modified vanilla anm2?

**Comment by Zamiell** [comment]
bite isn't considered to be a major tournament because it includes diversity, which is more luck based than seeded/unseeded

**Comment by Rchardon** [comment]
> is ui_fortunepaper.anm2 a modified vanilla anm2?

yes

**Comment by Zamiell** [comment]
then document what you changed at the top of the file.
see this as a reference for what to do:
https://github.com/Zamiell/racing-plus/blob/main/mod/resources/gfx/1000.039_heaven%20door%20custom.anm2

**Comment by Zamiell** [comment]
`removeFCBanners`

dont abbreviate here, use the full name of the file

**Comment by Zamiell** [comment]
postItemUse.ts

the name of the callback is useItem, not postItemUse

**Pull request merged**
