### PR TITLE
Show rerolled items for tracker

### PR DESCRIPTION
**Pull request by Rchardon**

### CODE REVIEW

**Comment by Rchardon** [comment]
This requires the PR on isaacscript-common

**Comment by Rchardon** [comment]
I did an update.sh but nothing changed. Is it because you haven't set a new version of isaacscript-common ?

**Comment by Zamiell** [comment]
yeah i can't publish i guess until i get home in a couple days

**Comment by Rchardon** [comment]
I don't know how to do for T Eden with his Birthright, if you wanna try it

**Comment by Zamiell** [comment]
thanks

**Pull request merged**
