### PR TITLE
Tainted dead laz fixes

### PR DESCRIPTION
**Pull request by Rchardon**

### CODE REVIEW

**Comment by Zamiell** [comment]
we need to cache all API calls in this PR like you did in the other one

**Comment by Zamiell** [comment]
```ts
function postPlayerChange(player: EntityPlayer) {
  startWithD6.postPlayerChange(player);
  const character = player.GetPlayerType();

  if (character === PlayerType.PLAYER_LAZARUS2_B && !g.run.laz2BGotItems) {
    giveFormatItems(player);
    player.AddCollectible(CollectibleType.COLLECTIBLE_D6, 6);
    g.run.laz2BGotItems = true;
  }
}
```

api calls need to be cached at the top of the function, like this:

```ts
function postPlayerChange(player: EntityPlayer) {
  const character = player.GetPlayerType();

  startWithD6.postPlayerChange(player);

  if (character === PlayerType.PLAYER_LAZARUS2_B && !g.run.laz2BGotItems) {
    giveFormatItems(player);
    player.AddCollectible(CollectibleType.COLLECTIBLE_D6, 6);
    g.run.laz2BGotItems = true;
  }
}
```

**Comment by Zamiell** [comment]
can we rename laz2BGotItems to laz2BGotStartingRaceItems ? thats a less confusing name i think

**Comment by Zamiell** [comment]
this PR has the same problem as the other ones - you are putting logic inside of a callback file (postPlayerChange.ts).
there shouldn't be logic in callback files!
this is a race feature, so
1) it should be invoked from a race callback, not the generic callback
2) and the logic itself should be in an appropriate file in the race callback

**Comment by Zamiell** [comment]
now and the branch has conflicts bcuz i merged some other PR

**Comment by Zamiell** [comment]
we can potentially simply this PR by:

1) giving the d6 / race starting items to Laz2
2) flipping
3) giving the d6 / race starting items to Laz2
4) flipping
5) muting the sound effect
6) canceling the animation

let me know if you can do it.
this is a better solution because then we can delete the laz2BGotStartingRaceItems variable.

**Comment by Rchardon** [comment]
I'll let it to you, it will be cleaner

**Comment by Zamiell** [comment]
it won't work, i tried it

for now, i'll make a custom callback
refactor the PR and add things to do on the first flip below this line:

https://github.com/Zamiell/racing-plus/blob/main/src/customCallbacks/postFlip.ts#L20

**Pull request merged**
