### PR TITLE
Fix perma death on krampus

### PR DESCRIPTION
**Pull request by Rchardon**

### CODE REVIEW

**Comment by Zamiell** [comment]
did you test this? the animation is longer than 2 seconds

**Comment by Rchardon** [comment]
It works but the problem was on Losts characters. So even with 2 sec you can still die permanently once outside the devil deal. So i think i will just add a check on lost since you can die from a devil deal with them

**Comment by Zamiell** [comment]
do you meant the opposite?

**Comment by Rchardon** [comment]
yeah can't * mb

**Comment by Zamiell** [comment]
how many seconds is the animation

**Comment by Rchardon** [comment]
1.3 sec

**Comment by Zamiell** [comment]
ok can you put that in a command then next to the 2 second definition and say that we round up to 2 seconds "to be safe"

**Comment by Rchardon** [comment]
Wait before accepting the PR, i need to add the check to Tainted Jacob lost form

**Comment by Zamiell** [comment]
oh i think there is an isaacscript function for that

**Comment by Rchardon** [comment]
There isn't

**Comment by Zamiell** [comment]
one sec then

**Comment by Zamiell** [comment]
see my edits, i think putting it into a function is better

**Pull request merged**
